### ISSUE TITLE
How to use this fork?

### ISSUE THREAD

**Issue by amcsi** [nipwaayoni/elastic-apm-laravel#11]
I tried to use both the master and span-fixes branches here with the 7.1.* version of nipwaayoni/elastic-apm-php-agent, but I'm still getting the philkra/elastic-apm-laravel#66 issue about the missing method

**Comment by dstepe** [comment]
I'm literally working on a way around that right now. I hope to have something out for testing soon. I can't commit to today, but within a couple of days at least. I'll ping this issue with a request for help testing.

**Comment by dstepe** [comment]
There is branch ready for testing, with some caveats. I have run this locally with Laravel 7.13.0 and APM 7.7. I have not yet tested with any other versions of either.

Make sure to use the `7.0-dev` branch:

```
composer require nipwaayoni/elastic-apm-laravel:dev-7.0-dev
```

I'm very interested in feedback from your experience.

**Comment by amcsi** [comment]
So I just tried this, and here is the failure I get straight away: the Agent class's constructor expects the configs to be passed as a Config instance, whereas what's really happening is that configs are merged and passed as arrays.

**Comment by dstepe** [comment]
I'm working to get a 7.1 release of the APM Agent package done today or tomorrow. Once that is available, I'll also make a new release of this package to use it correctly. It's taken longer than I would have liked, but we're close.

**Comment by dstepe** [comment]
I just made new releases of both packages. Please try release 7.0 of this package. The documentation has been updated as well and there a number of changes if you used the previous `philkra` version.

I'm very interested in feedback. Real world usage of this package has been limited, but I felt it important to get a release out.

**Comment by amcsi** [comment]
@dstepe it seems to work :)

**Comment by dstepe** [comment]
Basic functionality is done, at least for a first release. I'm closing this issue so we can work specific issues reported through real world usage.
