### ISSUE TITLE
transactions.use-route-uri config option not being respected

### ISSUE THREAD

**Issue by amcsi** [nipwaayoni/elastic-apm-laravel#16]
I have `transactions.use_route_uri` set to true in the config, but I'm still getting URLs logged to elastic that are fully resolved.

```php
    'transactions' => [

        //This option will bundle transaction on the route name without variables
        'use_route_uri' => env('APM_USEROUTEURI', true),

    ],
```

![2020-06-22_11-56](https://user-images.githubusercontent.com/116494/85274621-7a10f780-b47f-11ea-8ade-0b4e829b08be.png)

Expected:
for those thumbnail URLs to show up merged as
`GET /api/v1/reports/{uuid}/preview_thumbnail`
or something similar

**Comment by dstepe** [comment]
Looking at the code, I'm not sure how this ever worked. However, I think the fix is relatively straight forward. The issue is that the transaction is being started in middleware at a point the current Laravel Route object is not fully defined. I think we can update the name after the call to `$next($request)`, at which point the we have a populated Route with the URI.

I see the comment in the config file is also misleading. This is about the Route URI, not the name. I don't see much use case for the using the Route name in the transaction. That's something internal to the code.

**Comment by science695** [comment]
I deal with this issue (not in laravel, but similar).

The full URI of the request may have id numbers or parameters that do not make it a different type of transaction.

I ended up adding to my integration this:
`$transaction->setTransactionName($name);`

Where $name was the route matching string that I pulled from my framework.

**Comment by dstepe** [comment]
I believe this is fixed in the 7.0.1 release being prepped. Are you able to try out that branch before I merge it?

**Comment by amcsi** [comment]
@dstepe Yes

Unfortunately it seems to crash when I return a JsonResponse:

```
[2020-06-23 16:09:42] local.ERROR: Argument 1 passed to Nipwaayoni\ElasticApmLaravel\Middleware\RecordTransaction::response() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /home/attila/0/ttg/channel-dynamics-api/vendor/nipwaayoni/elastic-apm-laravel/src/Middleware/RecordTransaction.php on line 71 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Nipwaayoni\\ElasticApmLaravel\\Middleware\\RecordTransaction::response() must be an instance of Illuminate\\Http\\Response, instance of Illuminate\\Http\\JsonResponse given, called in /home/attila/0/ttg/channel-dynamics-api/vendor/nipwaayoni/elastic-apm-laravel/src/Middleware/RecordTransaction.php on line 71 at /home/attila/0/ttg/channel-dynamics-api/vendor/nipwaayoni/elastic-apm-laravel/src/Middleware/RecordTransaction.php:110)
```

The problem is that unfortunately Laravel's JsonResponse does not extend Laravel's regular Response. It rather extends Symfony's JsonResponse.
So you'll likely need to accept this as the common ancestor class: `\Symfony\Component\HttpFoundation\Response`;

Once that's fixed, unfortunately I'll probably only be able to test again tomorrow.

**Comment by dstepe** [comment]
Sigh. I really want more tests on these packages. It should be fixed now. Thanks for testing.

**Comment by dstepe** [comment]
I've added a manual test for JsonResponse types to my sample application I use for manual validation. That also revealed an APM schema validation failure with numeric HTTP header values which I fixed. The JsonResponse is working for me now.

**Comment by amcsi** [comment]
Fantastic. There is no more error, and `transactions.use-route-uri` is doing its job now :)
