### ISSUE TITLE
Feature request: ability to set custom context on the request transaction

### ISSUE THREAD

**Issue by amcsi** [nipwaayoni/elastic-apm-laravel#17]
It would be great to be able to send some custom context. I would need this to be able to filter in Kibana by custom values that I'd submit.

I can see that in `\Nipwaayoni\ElasticApmLaravel\Middleware\RecordTransaction` there is no way to hook into the transaction from outside. Thus the only way I'd be able to solve this myself is to create my own middleware.

**Comment by dstepe** [comment]
Given how the Agent works, is it acceptable to provide the custom context to the Agent rather than the Transaction? Since the Agent is typically not persistent in PHP, the context effectively only applies to the current transaction. If so, we should be able to easily hook the Agent build process here:

https://github.com/nipwaayoni/elastic-apm-laravel/blob/master/src/Providers/ElasticApmServiceProvider.php#L70

We can add:

```php
$builder->withCustomContextData(array $context);
```

as documented here: https://github.com/nipwaayoni/elastic-apm-php-agent/blob/master/docs/agent.md

You would then register a function in the Laravel container of the expected name and return your context array.

**Comment by amcsi** [comment]
AFAIK the Agent is for all requests, whereas a Transaction is per-request. There is additional context I would like to provide for a request that would be different for other requests. E.g. the logged-in user's group id and/or tenant id.

Regarding the Agent itself, for me personally the environment and the app name are sufficient for identifying the app source of the log. But like I mentioned above, there's request-dependent specific stuff that I would like to log.

**Comment by dstepe** [comment]
I understand and agree. My comment was only about the nature of PHP transactions. Is it not the case that the Agent is recreated with each request/response? Therefore, in practice, there is a one-to-one relation between an instance of an Agent and a Transaction.

Semantically, I would prefer to do this properly. I was thinking my proposal would solve your problem in the short term, but we would still want to enable multiple Transactions within a single Laravel request at some point, and that would require custom contexts per Transaction.

**Comment by amcsi** [comment]
Oh I see what you're saying
So there's a way you can hook into the creation of the Agent to modify it after auth, but before the transaction is created? If so, that's personally good enough for my use-case; I would want to have a single transaction per request, and maybe add my own custom spans to the same transaction.

**Comment by dstepe** [comment]
I had to rethink my comment. My solution only works for data which can be determined during boot, which I don't think fits your need.

We do need to provide a means to get context data into the middleware after the request has been processed. I think it would work to declare a context collection in your service provider and then the middleware can acquire it from the container. I think there is some work to do in the Agent package in support of this. I'll poke around and hopefully have something that works in a couple of days.

**Comment by amcsi** [comment]
Just saying that making your middleware extendable and exposing some protected method(s) to gain access to the transaction could work too. But of course it's up to you to decide the best approach.

**Comment by dstepe** [comment]
That does make sense. I need to start thinking from the perspective of a library provider. That seems like a better route to go to start with.

**Comment by dstepe** [comment]
I believe this is fixed in the 7.0.1 release being prepped. Are you able to try out that branch before I merge it?

**Comment by amcsi** [comment]
@dstepe see what I wrote here: #16

**Comment by amcsi** [comment]
Great, I was able to hook into the extended middleware really easily and achieve this:

![2020-06-23_19-59](https://user-images.githubusercontent.com/116494/85438278-19231580-b58c-11ea-9b52-d5aefb61f1cb.png)

One little nitpick (though not super important) is that this seemed to end up prefixed with `transaction.` in elastic/kibana. Is that normal for Elastic APM? I didn't prefix anything with transaction, and I can't seem to see anything in your code that would prepend "transaction" to anything.
In any case it's not a big deal, because it's equally index-able in this format too.

**Comment by dstepe** [comment]
I noticed that as well. I believe it's the APM side doing it.

https://www.elastic.co/guide/en/apm/get-started/current/metadata.html#custom-fields

It states:

```
Elasticsearch fields: transaction.custom | error.custom
```

So I believe it takes the provided `custom` context and places it under the `transaction.custom` key in the document.
