### ISSUE TITLE
Integration of the official APM PHP package

### ISSUE THREAD

**Issue by petericebear** [nipwaayoni/elastic-apm-laravel#24]
Hi,

Any plans to integrate the official PHP APM package of Elastic?
https://github.com/elastic/apm-agent-php

**Comment by dstepe** [comment]
That work was brought to my attention last week. I'm excited to see it happening since there are fairly significant limits on what we can do in pure PHP. The extension they are building should really improve the capability and I'll be watching it.

**Comment by dstepe** [comment]
This package is being abandoned. Please consider switching to https://github.com/arkaitzgarro/elastic-apm-laravel
