### ISSUE TITLE
Config environment is not overridable

### ISSUE THREAD

**Issue by pendolf** [nipwaayoni/elastic-apm-laravel#26]
When I set `APM_ENVIRONMENT=test` in the APM it always shows "development". Even when I update the default value in config
`'environment'   => env('APM_ENVIRONMENT', 'test'),` it's still shows "development". Probably this issue related to https://github.com/nipwaayoni/elastic-apm-laravel/blob/master/docs/configuration.md

**Comment by amcsi** [comment]
@pendolf move

` 'environment'   => env('APM_ENVIRONMENT', 'development'),`

into the `'server' => [` array.

It seems like apm-config.php provided by the library hasn't been updated yet :/

**Comment by dstepe** [comment]
Apologies. I see what happened. It was a result of my desire to clean up the `env.env.environment` nesting and I did not test adequately. The suggestions to place the environment in the `server` array should work, but I'll fix the underlying issue in the next release so the implementation is consistent with the currently presented config file.
